files:
  - source: /DodoPizza/**/ru.lproj/*.strings
    translation: /DodoPizza/**/%two_letters_code%.lproj/%original_file_name%
  - source: /DodoPizza/**/ru.lproj/*.stringsdict
    translation: /DodoPizza/**/%two_letters_code%.lproj/%original_file_name%
