preserve_hierarchy: true
files:
  - source: /transfolder4/*.de.xlf
    translation: /transfolder4/%file_name%.%two_letters_code%.xlf
    translation_replace:
      de.: gurk
    content_segmentation: 0
    translatable_elements: /xliff/file/body/trans-unit/target
    languages_mapping:
      two_letters_code:
        de: de
        uk: uk
    update_option: update_as_unapproved
